# templates/remove-docker-socket-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remove-docker-socket-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remove-docker-socket-role
subjects:
  - kind: ServiceAccount
    name: push-images-sa
    namespace: {{ .Values.daemonset.namespace }}
